[package]
authors = ["depthbomb <depthbomb@super.fish>"]
edition = "2024"
name = "nativelib"

[lib]
crate-type = ["cdylib"]

[dependencies]
napi = { version = "3.8.1", features = ["async"] }
napi-derive = "3.5.0"

[dependencies.windows]
version = "0.62.2"
features = [
	"Win32_Foundation",
	"Win32_System_Diagnostics_ToolHelp"
]

[build-dependencies]
napi-build = "2.3.1"

[profile.release]
lto = true
strip = "symbols"
